<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class TeknisiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing records for clean seeding (disable foreign key checks temporarily)
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        DB::table('teknisis')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1');

        // Pre-hash passwords to avoid repetitive hashing
        $password = Hash::make('password123');
        $now = Carbon::now();

        // Use raw SQL insert for maximum performance
        $teknisis = [
            [
                'nip' => '199001012015011001',
                'name' => 'Andi Wijaya, S.Kom.',
                'email' => 'andi.wijaya@kemlu.go.id',
                'phone' => '+62-21-3844001',
                'department' => 'Pusat Data dan Informasi',
                'position' => 'Senior IT Support Specialist',
                'status' => 'active',
                'skill_level' => 'expert',
                'skills' => '["Network Administration","System Administration","Database Management","Security Management","Cloud Computing","Virtualization"]',
                'certifications' => '["Cisco Certified Network Professional (CCNP)","Microsoft Certified Solutions Expert (MCSE)","CompTIA Security+","Oracle Database Administrator Certified","AWS Certified Solutions Architect"]',
                'ticket_count' => 245,
                'rating' => 4.8,
                'experience_years' => 8,
                'bio' => 'Senior IT specialist dengan pengalaman lebih dari 8 tahun di bidang network dan system administration.',
                'last_active_at' => $now->copy()->subMinutes(30),
                'password' => $password,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '199102152015012002',
                'name' => 'Budi Santoso, S.T.',
                'email' => 'budi.santoso.tech@kemlu.go.id',
                'phone' => '+62-21-3844002',
                'department' => 'Pusat Data dan Informasi',
                'position' => 'IT Support Specialist',
                'status' => 'active',
                'skill_level' => 'senior',
                'skills' => '["Hardware Support","Software Installation","Operating Systems","Basic Networking","User Training"]',
                'certifications' => '["CompTIA A+","Microsoft Certified Professional (MCP)","ITIL Foundation"]',
                'ticket_count' => 189,
                'rating' => 4.6,
                'experience_years' => 6,
                'bio' => 'Teknisi senior dengan fokus pada hardware support dan user assistance.',
                'last_active_at' => $now->copy()->subHours(2),
                'password' => $password,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '199203202015013003',
                'name' => 'Citra Kirana, S.Kom.',
                'email' => 'citra.kirana@kemlu.go.id',
                'phone' => '+62-21-3844003',
                'department' => 'Pusat Data dan Informasi',
                'position' => 'Software Support Specialist',
                'status' => 'active',
                'skill_level' => 'senior',
                'skills' => '["Application Support","Web Development","Database Administration","Scripting","API Integration"]',
                'certifications' => '["Oracle Certified Professional","Microsoft Certified Azure Developer","PHP Certified Developer"]',
                'ticket_count' => 156,
                'rating' => 4.7,
                'experience_years' => 5,
                'bio' => 'Spesialis software support dengan keahlian di web development dan database.',
                'last_active_at' => $now->copy()->subMinutes(45),
                'password' => $password,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '199304252015014004',
                'name' => 'Doni Ramadhan, S.T.',
                'email' => 'doni.ramadhan@kemlu.go.id',
                'phone' => '+62-21-3844004',
                'department' => 'Pusat Data dan Informasi',
                'position' => 'Network Support Specialist',
                'status' => 'active',
                'skill_level' => 'senior',
                'skills' => '["Network Infrastructure","Security Systems","Firewall Management","VPN Configuration","Network Monitoring"]',
                'certifications' => '["Cisco Certified Network Associate (CCNA)","CompTIA Network+","Certified Ethical Hacker (CEH)","Palo Alto Networks Certified"]',
                'ticket_count' => 134,
                'rating' => 4.5,
                'experience_years' => 4,
                'bio' => 'Spesialis network dengan fokus pada security dan infrastructure.',
                'last_active_at' => $now->copy()->subHours(1),
                'password' => $password,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '199505102015015005',
                'name' => 'Eva Sari Dewi, S.Kom.',
                'email' => 'eva.dewi@kemlu.go.id',
                'phone' => '+62-21-3844005',
                'department' => 'Pusat Data dan Informasi',
                'position' => 'Junior IT Support',
                'status' => 'active',
                'skill_level' => 'junior',
                'skills' => '["Basic Hardware Support","Software Installation","User Assistance","Documentation","Basic Troubleshooting"]',
                'certifications' => '["CompTIA IT Fundamentals","Microsoft Office Specialist"]',
                'ticket_count' => 78,
                'rating' => 4.3,
                'experience_years' => 2,
                'bio' => 'Junior IT support yang sedang berkembang dengan fokus pada user assistance.',
                'last_active_at' => $now->copy()->subMinutes(15),
                'password' => $password,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '199606152015016006',
                'name' => 'Fajar Nugroho, S.T.',
                'email' => 'fajar.nugroho@kemlu.go.id',
                'phone' => '+62-21-3844006',
                'department' => 'Pusat Data dan Informasi',
                'position' => 'Security Specialist',
                'status' => 'active',
                'skill_level' => 'expert',
                'skills' => '["Cybersecurity","Penetration Testing","Security Auditing","Risk Assessment","Compliance Management"]',
                'certifications' => '["Certified Information Systems Security Professional (CISSP)","Certified Ethical Hacker (CEH)","CompTIA Security+","GIAC Security Essentials (GSEC)"]',
                'ticket_count' => 92,
                'rating' => 4.9,
                'experience_years' => 7,
                'bio' => 'Security expert dengan spesialisasi di cybersecurity dan compliance.',
                'last_active_at' => $now->copy()->subHours(3),
                'password' => $password,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '199707202015017007',
                'name' => 'Gita Permata, S.Kom.',
                'email' => 'gita.permata@kemlu.go.id',
                'phone' => '+62-21-3844007',
                'department' => 'Pusat Data dan Informasi',
                'position' => 'Database Administrator',
                'status' => 'active',
                'skill_level' => 'senior',
                'skills' => '["Database Design","Performance Tuning","Backup and Recovery","Data Migration","SQL Programming"]',
                'certifications' => '["Oracle Database Administrator Certified Professional","Microsoft SQL Server Certified","PostgreSQL Certified"]',
                'ticket_count' => 67,
                'rating' => 4.6,
                'experience_years' => 5,
                'bio' => 'Database administrator dengan pengalaman di berbagai platform database.',
                'last_active_at' => $now->copy()->subMinutes(20),
                'password' => $password,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '199708252015018008',
                'name' => 'Hadi Saputra, S.T.',
                'email' => 'hadi.saputra@kemlu.go.id',
                'phone' => '+62-21-3844008',
                'department' => 'Pusat Data dan Informasi',
                'position' => 'System Administrator',
                'status' => 'active',
                'skill_level' => 'senior',
                'skills' => '["Linux Administration","Windows Server","Active Directory","PowerShell Scripting","Server Virtualization"]',
                'certifications' => '["Red Hat Certified Engineer (RHCE)","Microsoft Certified Solutions Associate (MCSA)","VMware Certified Professional"]',
                'ticket_count' => 145,
                'rating' => 4.4,
                'experience_years' => 6,
                'bio' => 'System administrator dengan keahlian di Linux dan Windows server environments.',
                'last_active_at' => $now->copy()->subHours(1),
                'password' => $password,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '199809102015019009',
                'name' => 'Indah Lestari, S.Kom.',
                'email' => 'indah.lestari@kemlu.go.id',
                'phone' => '+62-21-3844009',
                'department' => 'Pusat Data dan Informasi',
                'position' => 'Helpdesk Analyst',
                'status' => 'active',
                'skill_level' => 'junior',
                'skills' => '["Customer Service","Basic Troubleshooting","Ticket Management","Knowledge Base","Remote Support"]',
                'certifications' => '["ITIL Foundation","Helpdesk Institute Certified"]',
                'ticket_count' => 203,
                'rating' => 4.2,
                'experience_years' => 3,
                'bio' => 'Helpdesk analyst dengan fokus pada customer service dan first-level support.',
                'last_active_at' => $now->copy()->subMinutes(10),
                'password' => $password,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '199910152015011010',
                'name' => 'Joko Susilo, S.T.',
                'email' => 'joko.susilo@kemlu.go.id',
                'phone' => '+62-21-3844010',
                'department' => 'Pusat Data dan Informasi',
                'position' => 'Cloud Specialist',
                'status' => 'active',
                'skill_level' => 'senior',
                'skills' => '["Cloud Architecture","DevOps","Containerization","CI/CD Pipelines","Infrastructure as Code"]',
                'certifications' => '["AWS Certified DevOps Engineer","Google Cloud Professional","Kubernetes Certified Administrator","Docker Certified Associate"]',
                'ticket_count' => 87,
                'rating' => 4.7,
                'experience_years' => 4,
                'bio' => 'Cloud specialist dengan keahlian di AWS, Azure, dan Google Cloud Platform.',
                'last_active_at' => $now->copy()->subHours(2),
                'password' => $password,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        // Single bulk insert for maximum performance
        DB::table('teknisis')->insert($teknisis);
    }
}