<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class TeknisiSeeder extends Seeder
{
    public function run(): void
    {
        $password = Hash::make('password123');
        $now = Carbon::now();

        $teknisis = [
            [
                'nip' => '199001012015011001',
                'name' => 'Andi Wijaya, S.Kom.',
                'email' => 'andi.wijaya@kemlu.go.id',
                'phone' => '+62-21-3844001',
                'department' => 'Pusat Data dan Informasi',
                'position' => 'Senior IT Support Specialist',
                'status' => 'active',
                'skill_level' => 'expert',
                'skills' => json_encode(['Network Administration', 'System Administration', 'Database Management']),
                'certifications' => json_encode(['CCNP', 'MCSE', 'CompTIA Security+']),
                'ticket_count' => 245,
                'current_ticket_count' => 3,
                'rating' => 4.8,
                'experience_years' => 8,
                'bio' => 'Senior IT specialist.',
                'last_active_at' => $now,
                'password' => $password,
                'max_concurrent_tickets' => 10,
                'specializations' => json_encode(['Network', 'Security']),
                'performance_metrics' => json_encode(['avg_resolution_time' => 45]),
                'availability_status' => 'available',
                'workload_score' => 30.0,
                'is_available' => true,
                'current_workload' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '199102152015012002',
                'name' => 'Budi Santoso, S.T.',
                'email' => 'budi.santoso.tech@kemlu.go.id',
                'phone' => '+62-21-3844002',
                'department' => 'Pusat Data dan Informasi',
                'position' => 'IT Support Specialist',
                'status' => 'active',
                'skill_level' => 'senior',
                'skills' => json_encode(['Hardware Support', 'Software Installation']),
                'certifications' => json_encode(['CompTIA A+', 'ITIL Foundation']),
                'ticket_count' => 189,
                'current_ticket_count' => 2,
                'rating' => 4.6,
                'experience_years' => 6,
                'bio' => 'Teknisi senior.',
                'last_active_at' => $now,
                'password' => $password,
                'max_concurrent_tickets' => 10,
                'specializations' => json_encode(['Hardware', 'Software']),
                'performance_metrics' => json_encode(['avg_resolution_time' => 60]),
                'availability_status' => 'available',
                'workload_score' => 20.0,
                'is_available' => true,
                'current_workload' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '199203202015013003',
                'name' => 'Citra Kirana, S.Kom.',
                'email' => 'citra.kirana@kemlu.go.id',
                'phone' => '+62-21-3844003',
                'department' => 'Pusat Data dan Informasi',
                'position' => 'Software Support Specialist',
                'status' => 'active',
                'skill_level' => 'senior',
                'skills' => json_encode(['Application Support', 'Web Development']),
                'certifications' => json_encode(['Oracle Certified Professional']),
                'ticket_count' => 156,
                'current_ticket_count' => 2,
                'rating' => 4.7,
                'experience_years' => 5,
                'bio' => 'Spesialis software support.',
                'last_active_at' => $now,
                'password' => $password,
                'max_concurrent_tickets' => 10,
                'specializations' => json_encode(['Software', 'Database']),
                'performance_metrics' => json_encode(['avg_resolution_time' => 55]),
                'availability_status' => 'available',
                'workload_score' => 20.0,
                'is_available' => true,
                'current_workload' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '199304252015014004',
                'name' => 'Doni Ramadhan, S.T.',
                'email' => 'doni.ramadhan@kemlu.go.id',
                'phone' => '+62-21-3844004',
                'department' => 'Pusat Data dan Informasi',
                'position' => 'Network Support Specialist',
                'status' => 'active',
                'skill_level' => 'senior',
                'skills' => json_encode(['Network Infrastructure', 'Security Systems']),
                'certifications' => json_encode(['CCNA', 'CompTIA Network+']),
                'ticket_count' => 134,
                'current_ticket_count' => 2,
                'rating' => 4.5,
                'experience_years' => 4,
                'bio' => 'Spesialis network.',
                'last_active_at' => $now,
                'password' => $password,
                'max_concurrent_tickets' => 10,
                'specializations' => json_encode(['Network', 'Infrastructure']),
                'performance_metrics' => json_encode(['avg_resolution_time' => 50]),
                'availability_status' => 'available',
                'workload_score' => 20.0,
                'is_available' => true,
                'current_workload' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '199505102015015005',
                'name' => 'Eva Sari Dewi, S.Kom.',
                'email' => 'eva.dewi@kemlu.go.id',
                'phone' => '+62-21-3844005',
                'department' => 'Pusat Data dan Informasi',
                'position' => 'Junior IT Support',
                'status' => 'active',
                'skill_level' => 'junior',
                'skills' => json_encode(['Basic Hardware Support', 'Software Installation']),
                'certifications' => json_encode(['CompTIA IT Fundamentals']),
                'ticket_count' => 78,
                'current_ticket_count' => 1,
                'rating' => 4.3,
                'experience_years' => 2,
                'bio' => 'Junior IT support.',
                'last_active_at' => $now,
                'password' => $password,
                'max_concurrent_tickets' => 8,
                'specializations' => json_encode(['Support', 'Documentation']),
                'performance_metrics' => json_encode(['avg_resolution_time' => 70]),
                'availability_status' => 'available',
                'workload_score' => 12.5,
                'is_available' => true,
                'current_workload' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '199606152015016006',
                'name' => 'Fajar Nugroho, S.T.',
                'email' => 'fajar.nugroho@kemlu.go.id',
                'phone' => '+62-21-3844006',
                'department' => 'Pusat Data dan Informasi',
                'position' => 'Security Specialist',
                'status' => 'active',
                'skill_level' => 'expert',
                'skills' => json_encode(['Cybersecurity', 'Penetration Testing']),
                'certifications' => json_encode(['CISSP', 'CEH', 'CompTIA Security+']),
                'ticket_count' => 92,
                'current_ticket_count' => 1,
                'rating' => 4.9,
                'experience_years' => 7,
                'bio' => 'Security expert.',
                'last_active_at' => $now,
                'password' => $password,
                'max_concurrent_tickets' => 10,
                'specializations' => json_encode(['Security', 'Compliance']),
                'performance_metrics' => json_encode(['avg_resolution_time' => 40]),
                'availability_status' => 'available',
                'workload_score' => 10.0,
                'is_available' => true,
                'current_workload' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '199707202015017007',
                'name' => 'Gita Permata, S.Kom.',
                'email' => 'gita.permata@kemlu.go.id',
                'phone' => '+62-21-3844007',
                'department' => 'Pusat Data dan Informasi',
                'position' => 'Database Administrator',
                'status' => 'active',
                'skill_level' => 'senior',
                'skills' => json_encode(['Database Design', 'Performance Tuning']),
                'certifications' => json_encode(['Oracle DBA', 'SQL Server Certified']),
                'ticket_count' => 67,
                'current_ticket_count' => 1,
                'rating' => 4.6,
                'experience_years' => 5,
                'bio' => 'Database administrator.',
                'last_active_at' => $now,
                'password' => $password,
                'max_concurrent_tickets' => 10,
                'specializations' => json_encode(['Database', 'Performance']),
                'performance_metrics' => json_encode(['avg_resolution_time' => 65]),
                'availability_status' => 'available',
                'workload_score' => 10.0,
                'is_available' => true,
                'current_workload' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '199708252015018008',
                'name' => 'Hadi Saputra, S.T.',
                'email' => 'hadi.saputra@kemlu.go.id',
                'phone' => '+62-21-3844008',
                'department' => 'Pusat Data dan Informasi',
                'position' => 'System Administrator',
                'status' => 'active',
                'skill_level' => 'senior',
                'skills' => json_encode(['Linux Administration', 'Windows Server']),
                'certifications' => json_encode(['RHCE', 'MCSA', 'VMware VCP']),
                'ticket_count' => 145,
                'current_ticket_count' => 2,
                'rating' => 4.4,
                'experience_years' => 6,
                'bio' => 'System administrator.',
                'last_active_at' => $now,
                'password' => $password,
                'max_concurrent_tickets' => 10,
                'specializations' => json_encode(['System', 'Server']),
                'performance_metrics' => json_encode(['avg_resolution_time' => 55]),
                'availability_status' => 'available',
                'workload_score' => 20.0,
                'is_available' => true,
                'current_workload' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '199809102015019009',
                'name' => 'Indah Lestari, S.Kom.',
                'email' => 'indah.lestari@kemlu.go.id',
                'phone' => '+62-21-3844009',
                'department' => 'Pusat Data dan Informasi',
                'position' => 'Helpdesk Analyst',
                'status' => 'active',
                'skill_level' => 'junior',
                'skills' => json_encode(['Customer Service', 'Basic Troubleshooting']),
                'certifications' => json_encode(['ITIL Foundation']),
                'ticket_count' => 203,
                'current_ticket_count' => 3,
                'rating' => 4.2,
                'experience_years' => 3,
                'bio' => 'Helpdesk analyst.',
                'last_active_at' => $now,
                'password' => $password,
                'max_concurrent_tickets' => 8,
                'specializations' => json_encode(['Helpdesk', 'Support']),
                'performance_metrics' => json_encode(['avg_resolution_time' => 35]),
                'availability_status' => 'available',
                'workload_score' => 37.5,
                'is_available' => true,
                'current_workload' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '199910152015011010',
                'name' => 'Joko Susilo, S.T.',
                'email' => 'joko.susilo@kemlu.go.id',
                'phone' => '+62-21-3844010',
                'department' => 'Pusat Data dan Informasi',
                'position' => 'Cloud Specialist',
                'status' => 'active',
                'skill_level' => 'senior',
                'skills' => json_encode(['Cloud Architecture', 'DevOps']),
                'certifications' => json_encode(['AWS DevOps', 'GCP Professional', 'CKA']),
                'ticket_count' => 87,
                'current_ticket_count' => 1,
                'rating' => 4.7,
                'experience_years' => 4,
                'bio' => 'Cloud specialist.',
                'last_active_at' => $now,
                'password' => $password,
                'max_concurrent_tickets' => 10,
                'specializations' => json_encode(['Cloud', 'DevOps']),
                'performance_metrics' => json_encode(['avg_resolution_time' => 50]),
                'availability_status' => 'available',
                'workload_score' => 10.0,
                'is_available' => true,
                'current_workload' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('teknisis')->insert($teknisis);
    }
}
